# -*- coding: utf-8 -*-
"""DS lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zRBx4heyiUHfM_TZBY9jFcn4ohhsOTyf
"""

print("abcd")

